-- RootScope baseline schema. Portable across H2 (dev/test) and PostgreSQL (prod):
-- identity PKs, TIMESTAMPTZ instants, TEXT payloads. Event times live in
-- occurred_at: TIMESTAMP is a reserved word and stays out of the schema.

CREATE TABLE services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  team VARCHAR(255),
  repository VARCHAR(255),
  CONSTRAINT uq_services_name UNIQUE (name)
);

CREATE TABLE deployments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_id BIGINT NOT NULL,
  version VARCHAR(255) NOT NULL,
  commit_hash VARCHAR(255),
  author VARCHAR(255),
  occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT fk_deployments_service FOREIGN KEY (service_id) REFERENCES services (id)
);

CREATE TABLE events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_id BIGINT NOT NULL,
  type VARCHAR(255) NOT NULL,
  occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
  severity DOUBLE PRECISION NOT NULL,
  payload TEXT,
  CONSTRAINT fk_events_service FOREIGN KEY (service_id) REFERENCES services (id)
);
CREATE INDEX ix_events_occurred_at ON events (occurred_at);

CREATE TABLE incidents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  severity VARCHAR(255) NOT NULL,
  service_id BIGINT NOT NULL,
  started_at TIMESTAMP WITH TIME ZONE NOT NULL,
  resolved_at TIMESTAMP WITH TIME ZONE,
  CONSTRAINT fk_incidents_service FOREIGN KEY (service_id) REFERENCES services (id)
);

CREATE TABLE correlations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  incident_id BIGINT NOT NULL,
  event_id BIGINT NOT NULL,
  score DOUBLE PRECISION NOT NULL,
  temporal DOUBLE PRECISION NOT NULL,
  dependency DOUBLE PRECISION NOT NULL,
  anomaly DOUBLE PRECISION NOT NULL,
  error_corr DOUBLE PRECISION NOT NULL,
  deployment DOUBLE PRECISION NOT NULL,
  reason TEXT,
  CONSTRAINT fk_correlations_incident FOREIGN KEY (incident_id) REFERENCES incidents (id),
  CONSTRAINT fk_correlations_event FOREIGN KEY (event_id) REFERENCES events (id)
);
CREATE INDEX ix_correlations_incident ON correlations (incident_id);

CREATE TABLE dependencies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_service_id BIGINT NOT NULL,
  to_service_id BIGINT NOT NULL,
  CONSTRAINT uq_dependencies_pair UNIQUE (from_service_id, to_service_id),
  CONSTRAINT fk_dependencies_from FOREIGN KEY (from_service_id) REFERENCES services (id),
  CONSTRAINT fk_dependencies_to FOREIGN KEY (to_service_id) REFERENCES services (id)
);
